### ISSUE TITLE
EULER ANGLES IN BROAD

### ISSUE THREAD

**Issue by logindiamant** [dlaidig/broad#3]
Dear colleagues, please tell us, how to calculate Euler angles from opt_quat in BROAD datasets? May be, you heave some MATLAB script?

**Comment by dlaidig** [comment]
I'm not using Matlab but I have seen that you have received some pointers for the conversion of quaternions to Euler angles in https://github.com/marcocaruso/mimu_optical_dataset_caruso_sassari/issues/2 and https://github.com/agnieszkaszczesna/RepoIMU/issues/1.

The BROAD dataset does not make use of Euler angles but stores the reference orientations as quaternions and includes Python code for quaternion-based calculation of the orientation estimation error. Without more details, I cannot provide help about which Euler angles to choose. However, as a general advice, I would be very careful for using Euler angles to compare different orientations. With the wide range of orientations found in the dataset, any of the possible rotation axis sequences will likely be close to gimbal lock from time to time.
