### ISSUE TITLE
NaN value in .mat file

### ISSUE THREAD

**Issue by hoangvietdo** [dlaidig/broad#4]
Thanks for sharing your incredible work!

I've witnessed some ```NaN``` values in the .mat file (e.g., dataset number ```01``` and ```04```).
Is it a bug, or there are some underlying reasons for this?

**Comment by dlaidig** [comment]
Thanks for looking into the BROAD dataset! :)

If I'm not mistaken, the `NaN` values should only appear in `opt_quat` and `opt_pos`. Those values indicate short gaps in which the optical motion capture system failed to track at least one of the reflective markers. We decided to not fill those gaps using interpolation but instead exclude the corresponding samples from the error calculation. This can easily be done in Python and Matlab by using the `nanmean` function for the RMSE calculation:

https://github.com/dlaidig/broad/blob/6738875895e821afda12a5dd1b186092c6cff6a4/example_code/broad_utils.py#L166

Could you please confirm that the `NaN` values you found are indeed short gaps in the optical reference data?

**Comment by hoangvietdo** [comment]
Thanks for your fast response!

I indeed found the ```NaN``` value in the ```opt_quat```.
When I convert them to the Euler angle and plot them, I witness a lot of discontinuous parts due to the ```NaN``` value.

I'm fully aware of the problem with the optical system, so I can somehow guess the reason.

Thanks for your information.
